package com.softdream.exposicily.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val expoSicilyLightPrimary = Color(0xFF825500)
val expoSicilyLightOnPrimary = Color(0xFFFFFFFF)
val expoSicilyLightPrimaryContainer = Color(0xFFFFDDAE)
val expoSicilyLightOnPrimaryContainer = Color(0xFF2A1800)
val expoSicilyLightSecondary = Color(0xFF6F5B40)
val expoSicilyLightOnSecondary = Color(0xFFFFFFFF)
val expoSicilyLightSecondaryContainer = Color(0xFFFADEBC)
val expoSicilyLightOnSecondaryContainer = Color(0xFF271904)
val expoSicilyLightTertiary = Color(0xFF516440)
val expoSicilyLightOnTertiary = Color(0xFFFFFFFF)
val expoSicilyLightTertiaryContainer = Color(0xFFD3EABC)
val expoSicilyLightOnTertiaryContainer = Color(0xFF102004)
val expoSicilyLightError = Color(0xFFBA1B1B)
val expoSicilyLightErrorContainer = Color(0xFFFFDAD4)
val expoSicilyLightOnError = Color(0xFFFFFFFF)
val expoSicilyLightOnErrorContainer = Color(0xFF410001)
val expoSicilyLightBackground = Color(0xFFFCFCFC)
val expoSicilyLightOnBackground = Color(0xFF1F1B16)
val expoSicilyLightSurface = Color(0xFFFCFCFC)
val expoSicilyLightOnSurface = Color(0xFF1F1B16)
val expoSicilyLightSurfaceVariant = Color(0xFFF0E0CF)
val expoSicilyLightOnSurfaceVariant = Color(0xFF4F4539)
val expoSicilyLightOutline = Color(0xFF817567)
val expoSicilyLightInverseOnSurface = Color(0xFFF9EFE6)
val expoSicilyLightInverseSurface = Color(0xFF34302A)
val expoSicilyLightPrimaryInverse = Color(0xFFFFB945)

val expoSicilyDarkPrimary = Color(0xFFFFB945)
val expoSicilyDarkOnPrimary = Color(0xFF452B00)
val expoSicilyDarkPrimaryContainer = Color(0xFF624000)
val expoSicilyDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val expoSicilyDarkSecondary = Color(0xFFDDC3A2)
val expoSicilyDarkOnSecondary = Color(0xFF3E2E16)
val expoSicilyDarkSecondaryContainer = Color(0xFF56442B)
val expoSicilyDarkOnSecondaryContainer = Color(0xFFFADEBC)
val expoSicilyDarkTertiary = Color(0xFFB8CEA2)
val expoSicilyDarkOnTertiary = Color(0xFF243516)
val expoSicilyDarkTertiaryContainer = Color(0xFF3A4C2B)
val expoSicilyDarkOnTertiaryContainer = Color(0xFFD3EABC)
val expoSicilyDarkError = Color(0xFFFFB4A9)
val expoSicilyDarkErrorContainer = Color(0xFF930006)
val expoSicilyDarkOnError = Color(0xFF680003)
val expoSicilyDarkOnErrorContainer = Color(0xFFFFDAD4)
val expoSicilyDarkBackground = Color(0xFF1F1B16)
val expoSicilyDarkOnBackground = Color(0xFFEAE1D9)
val expoSicilyDarkSurface = Color(0xFF1F1B16)
val expoSicilyDarkOnSurface = Color(0xFFEAE1D9)
val expoSicilyDarkSurfaceVariant = Color(0xFF4F4539)
val expoSicilyDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val expoSicilyDarkOutline = Color(0xFF9C8F80)
val expoSicilyDarkInverseOnSurface = Color(0xFF32281A)
val expoSicilyDarkInverseSurface = Color(0xFFEAE1D9)
val expoSicilyDarkPrimaryInverse = Color(0xFF624000)