package com.softdream.worldlocations.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val worldLocationsLightPrimary = Color(0xFF825500)
val worldLocationsLightOnPrimary = Color(0xFFFFFFFF)
val worldLocationsLightPrimaryContainer = Color(0xFFFFDDAE)
val worldLocationsLightOnPrimaryContainer = Color(0xFF2A1800)
val worldLocationsLightSecondary = Color(0xFF6F5B40)
val worldLocationsLightOnSecondary = Color(0xFFFFFFFF)
val worldLocationsLightSecondaryContainer = Color(0xFFFADEBC)
val worldLocationsLightOnSecondaryContainer = Color(0xFF271904)
val worldLocationsLightTertiary = Color(0xFF516440)
val worldLocationsLightOnTertiary = Color(0xFFFFFFFF)
val worldLocationsLightTertiaryContainer = Color(0xFFD3EABC)
val worldLocationsLightOnTertiaryContainer = Color(0xFF102004)
val worldLocationsLightError = Color(0xFFBA1B1B)
val worldLocationsLightErrorContainer = Color(0xFFFFDAD4)
val worldLocationsLightOnError = Color(0xFFFFFFFF)
val worldLocationsLightOnErrorContainer = Color(0xFF410001)
val worldLocationsLightBackground = Color(0xFFFCFCFC)
val worldLocationsLightOnBackground = Color(0xFF1F1B16)
val worldLocationsLightSurface = Color(0xFFFCFCFC)
val worldLocationsLightOnSurface = Color(0xFF1F1B16)
val worldLocationsLightSurfaceVariant = Color(0xFFF0E0CF)
val worldLocationsLightOnSurfaceVariant = Color(0xFF4F4539)
val worldLocationsLightOutline = Color(0xFF817567)
val worldLocationsLightInverseOnSurface = Color(0xFFF9EFE6)
val worldLocationsLightInverseSurface = Color(0xFF34302A)
val worldLocationsLightPrimaryInverse = Color(0xFFFFB945)

val worldLocationsDarkPrimary = Color(0xFFFFB945)
val worldLocationsDarkOnPrimary = Color(0xFF452B00)
val worldLocationsDarkPrimaryContainer = Color(0xFF624000)
val worldLocationsDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val worldLocationsDarkSecondary = Color(0xFFDDC3A2)
val worldLocationsDarkOnSecondary = Color(0xFF3E2E16)
val worldLocationsDarkSecondaryContainer = Color(0xFF56442B)
val worldLocationsDarkOnSecondaryContainer = Color(0xFFFADEBC)
val worldLocationsDarkTertiary = Color(0xFFB8CEA2)
val worldLocationsDarkOnTertiary = Color(0xFF243516)
val worldLocationsDarkTertiaryContainer = Color(0xFF3A4C2B)
val worldLocationsDarkOnTertiaryContainer = Color(0xFFD3EABC)
val worldLocationsDarkError = Color(0xFFFFB4A9)
val worldLocationsDarkErrorContainer = Color(0xFF930006)
val worldLocationsDarkOnError = Color(0xFF680003)
val worldLocationsDarkOnErrorContainer = Color(0xFFFFDAD4)
val worldLocationsDarkBackground = Color(0xFF1F1B16)
val worldLocationsDarkOnBackground = Color(0xFFEAE1D9)
val worldLocationsDarkSurface = Color(0xFF1F1B16)
val worldLocationsDarkOnSurface = Color(0xFFEAE1D9)
val worldLocationsDarkSurfaceVariant = Color(0xFF4F4539)
val worldLocationsDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val worldLocationsDarkOutline = Color(0xFF9C8F80)
val worldLocationsDarkInverseOnSurface = Color(0xFF32281A)
val worldLocationsDarkInverseSurface = Color(0xFFEAE1D9)
val worldLocationsDarkPrimaryInverse = Color(0xFF624000)